=== SnappyDataInc/snappy-store/gemfirexd/tools/src/test/resources/lib/sqlResults1_0.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
This is the XML DTD for checking the output ResultSet of an SQL query.

All XMLs must include a DOCTYPE of the following form:

  <!DOCTYPE sqlResults PUBLIC
    "-//GemStone Systems, Inc.//GemFireXD Test Results 1.0//EN"
    "sqlResults1_0.dtd">

-->

<!--

The following conventions apply to all file elements unless indicated otherwise.

- In elements that contain PCDATA, leading and trailing whitespace in
  the data may be ignored.

- In elements whose value is an "enumerated type", the value is case
  sensitive.

-->

<!--
The "sqlResults" element is the root element of all the specified ResultSets.
It contains one or more "resultSet" elements each specifying a JDBC
ResultSet object.
-->
<!ELEMENT sqlResults (resultSet+)>

<!--
The "resultSet" element is the root element of the obtained ResultSet.
It must specify an ID attribute to identify a ResultSet. This is so that
a single XML file can specify multiple resultSet elements for different
test results. The optional "ordered" attribute specifies whether the result
is expected to be in exactly the order given in the XML or not.
-->

<!ELEMENT resultSet (row*)>
<!ATTLIST resultSet
  id ID #REQUIRED
  ordered (false | true) #IMPLIED>

<!--
The "row" element contains a single row of the ResultSet.
It contains one or more "field" elements.
-->

<!ELEMENT row (field+)>

<!--
The "field" element is contained within a "row" element and contains
the name and value. It can optionally also specify the type of the
expected object. Normally the value is a simple toString() on the
underlying java object though it can be any string representation
of the object in principle.
-->

<!ELEMENT field (#PCDATA)>
<!ATTLIST field
  name CDATA #REQUIRED
  type CDATA #IMPLIED>

=== SnappyDataInc/snappy-store/gemfirexd/tools/src/test/resources/lib/checkFunctions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlResults PUBLIC "-//GemStone Systems, Inc.//GemFireXD Test Results 1.0//EN"
          "sqlResults1_0.dtd">
<sqlResults>
	<resultSet id="q_1">
		<row>
			<field name="1">22</field>	
		</row>
		<row>	
			<field name="1">24</field>
		</row>
		<row>		
			<field name="1">26</field>
			
		</row>
		<row>		
			<field name="1">28</field>			
		</row>
	</resultSet>
	
	<resultSet id="q_2">
		<row>
			<field name="ID">11</field>
			<field name="SECURITY_ID">char11</field>	
		</row>
		<row>	
			<field name="ID">12</field>
			<field name="SECURITY_ID">char12</field>	
		</row>
		<row>		
			<field name="ID">13</field>
			<field name="SECURITY_ID">char13</field>	
			
		</row>
		<row>		
			<field name="ID">14</field>
			<field name="SECURITY_ID">char14</field>				
		</row>
	</resultSet>
	
	<resultSet id="q_3">
		<row>
			<field name="1">20</field>				
		</row>		
	</resultSet>
	
	<resultSet id="q_4">
		<row>
			<field name="1">1</field>				
		</row>		
	</resultSet>
</sqlResults>

=== SnappyDataInc/snappy-store/gemfirexd/tools/src/test/resources/lib/selectWithRedundancy2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlResults PUBLIC "-//GemStone Systems, Inc.//GemFireXD Test Results 1.0//EN"
          "sqlResults1_0.dtd">
<sqlResults>
        <resultSet id="q_1">
                <row>
                        <field name="CID">10</field>
                </row>
                <row>
                        <field name="CID">20</field>
                </row>
                <row>
                        <field name="CID">30</field>
                </row>
                <row>
                        <field name="CID">40</field>
                </row>
                <row>
                        <field name="CID">50</field>
                </row>
                <row>
                        <field name="CID">60</field>
                </row>
                <row>
                        <field name="CID">70</field>
                </row>
                <row>
                        <field name="CID">80</field>
                </row>
                <row>
                        <field name="CID">90</field>
                </row>
                <row>
                        <field name="CID">100</field>
                </row>
                <row>
                        <field name="CID">110</field>
                </row>
                <row>
                        <field name="CID">120</field>
                </row>
                 <row>
                        <field name="CID">130</field>
                </row>
                <row>
                        <field name="CID">140</field>
                </row>
                <row>
                        <field name="CID">150</field>
                </row>
                <row>
                        <field name="CID">160</field>
                </row>
                <row>
                        <field name="CID">170</field>
                </row>
                <row>
                        <field name="CID">180</field>
                </row>
        </resultSet>


        <resultSet id="q_2">
                <row>
                        <field name="CID">10</field>
                </row>
                <row>
                        <field name="CID">20</field>
                </row>
                <row>
                        <field name="CID">30</field>
                </row>
                <row>
                        <field name="CID">40</field>
                </row>
                <row>
                        <field name="CID">50</field>
                </row>
                <row>
                        <field name="CID">60</field>
                </row>
                <row>
                        <field name="CID">70</field>
                </row>
                <row>
                        <field name="CID">80</field>
                </row>
                <row>
                        <field name="CID">90</field>
                </row>
                <row>
                        <field name="CID">100</field>
                </row>
                <row>
                        <field name="CID">110</field>
                </row>
                <row>
                        <field name="CID">120</field>
                </row>
                 <row>
                        <field name="CID">130</field>
                </row>
                <row>
                        <field name="CID">140</field>
                </row>
                <row>
                        <field name="CID">150</field>
                </row>
                <row>
                        <field name="CID">160</field>
                </row>
                <row>
                        <field name="CID">170</field>
                </row>
                <row>
                        <field name="CID">180</field>
                </row>
                <row>
                        <field name="CID">190</field>
                </row>
        </resultSet>

        <resultSet id="q_3">
                <row>
                        <field name="CID">10</field>
                </row>
                <row>
                        <field name="CID">20</field>
                </row>
                <row>
                        <field name="CID">30</field>
                </row>
                <row>
                        <field name="CID">40</field>
                </row>
                <row>
                        <field name="CID">50</field>
                </row>
                <row>
                        <field name="CID">60</field>
                </row>
                <row>
                        <field name="CID">70</field>
                </row>
                <row>
                        <field name="CID">80</field>
                </row>
                <row>
                        <field name="CID">90</field>
                </row>
                <row>
                        <field name="CID">100</field>
                </row>
                <row>
                        <field name="CID">110</field>
                </row>
                <row>
                        <field name="CID">120</field>
                </row>
                 <row>
                        <field name="CID">130</field>
                </row>
                <row>
                        <field name="CID">140</field>
                </row>
                <row>
                        <field name="CID">150</field>
                </row>
                <row>
                        <field name="CID">160</field>
                </row>
                <row>
                        <field name="CID">170</field>
                </row>
                <row>
                        <field name="CID">180</field>
                </row>

        </resultSet>

        <resultSet id="q_4">
                <row>
                        <field name="CID">10</field>
                </row>
        </resultSet>


        <resultSet id="q_5">
                <row>
                        <field name="CID">10</field>
                </row>
                <row>
                        <field name="CID">20</field>
                </row>
        </resultSet>

</sqlResults>

=== SnappyDataInc/snappy-store/gemfirexd/tools/src/test/resources/lib/distributedQuery.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlResults PUBLIC "-//GemStone Systems, Inc.//GemFireXD Test Results 1.0//EN"
          "sqlResults1_0.dtd">
<sqlResults>
	<resultSet id="q_1">
		<row>
			<field name="ID">1</field>
			<field name="DESCRIPTION">First</field>
		</row>
		<row>
			<field name="ID">2</field>
			<field name="DESCRIPTION">Second</field>
		</row>
	</resultSet>
</sqlResults>

=== SnappyDataInc/snappy-store/gemfirexd/tools/src/test/resources/lib/checkEventCallback.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlResults PUBLIC "-//GemStone Systems, Inc.//GemFireXD Test Results 1.0//EN"
          "sqlResults1_0.dtd">
<sqlResults>

	<resultSet id="loader_get_1">
		<row>
			<field name="THIRDID">3</field>
		</row>
	</resultSet>
	
	<resultSet id="loader_get_2">
		<row>
			<field name="THIRDID">4</field>
		</row>
	</resultSet>
	
	<resultSet id="loader_get_3">
		<row>
			<field name="THIRDID">5</field>
		</row>
	</resultSet>	
	
	<resultSet id="loader_get">
		<row>
			<field name="ID">1</field>
			<field name="SECONDID">2</field>
			<field name="THIRDID">3</field>
		</row>
		<row>
			<field name="ID">2</field>
			<field name="SECONDID">3</field>
			<field name="THIRDID">4</field>
		</row>
		<row>
			<field name="ID">3</field>
			<field name="SECONDID">4</field>
			<field name="THIRDID">5</field>
		</row>
	</resultSet>
	
	<resultSet id="listenerWriter_Test_1">
		<row>
			<field name="ID">1</field>
			<field name="SECONDID">2</field>
			<field name="THIRDID">3</field>
		</row>
		<row>
			<field name="ID">2</field>
			<field name="SECONDID">3</field>
			<field name="THIRDID">4</field>
		</row>
		<row>
			<field name="ID">3</field>
			<field name="SECONDID">4</field>
			<field name="THIRDID">5</field>
		</row>
	</resultSet>
	
	<resultSet id="listenerWriter_Test_2">
		<row>
			<field name="ID">1</field>
			<field name="SECONDID">2</field>
			<field name="THIRDID">3</field>
		</row>
		<row>
			<field name="ID">2</field>
			<field name="SECONDID">3</field>
			<field name="THIRDID">4</field>
		</row>
		<row>
			<field name="ID">3</field>
			<field name="SECONDID">4</field>
			<field name="THIRDID">5</field>
		</row>
		<row>
			<field name="ID">5</field>
			<field name="SECONDID">6</field>
			<field name="THIRDID">7</field>
		</row>		
	</resultSet>
	
	<resultSet id="listenerWriter_Test_3">
		<row>
			<field name="ID">1</field>
			<field name="SECONDID">2</field>
			<field name="THIRDID">7</field>
		</row>
		<row>
			<field name="ID">2</field>
			<field name="SECONDID">3</field>
			<field name="THIRDID">4</field>
		</row>
		<row>
			<field name="ID">3</field>
			<field name="SECONDID">4</field>
			<field name="THIRDID">5</field>
		</row>
		<row>
			<field name="ID">5</field>
			<field name="SECONDID">6</field>
			<field name="THIRDID">7</field>
		</row>	
		<row>
			<field name="ID">6</field>
			<field name="SECONDID">7</field>
			<field name="THIRDID">8</field>
		</row>				
	</resultSet>

	<resultSet id="listenerWriter_Test_4">
		<row>
			<field name="ID">2</field>
			<field name="SECONDID">3</field>
			<field name="THIRDID">4</field>
		</row>
		<row>
			<field name="ID">3</field>
			<field name="SECONDID">4</field>
			<field name="THIRDID">5</field>
		</row>
		<row>
			<field name="ID">6</field>
			<field name="SECONDID">7</field>
			<field name="THIRDID">8</field>
		</row>				
	</resultSet>
	
</sqlResults>

=== SnappyDataInc/snappy-store/gemfirexd/tools/src/test/resources/lib/checkIndex.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlResults PUBLIC "-//GemStone Systems, Inc.//GemFireXD Test Results 1.0//EN"
          "sqlResults1_0.dtd">
<sqlResults>
  <!--
		Result expected from SYSCONGLOMERATES when creating a VOLUMEIDX index
		without GLOBAL HASH specification.
	-->
	<resultSet id="orders_nogh">
		<row>
			<field name="CONGLOMERATENAME">VOLUMEIDX</field>
			<field name="DESCRIPTOR">LOCALSORTEDMAP (2)</field>
		</row>
	</resultSet>
	<!--
		Result expected from SYSCONGLOMERATES when creating a VOLUMEIDX index
		with GLOBAL HASH specification.
	-->
	<resultSet id="orders_gh">
		<row>
			<field name="CONGLOMERATENAME">VOLUMEIDX</field>
			<field name="DESCRIPTOR">GLOBALHASH (2)</field>
		</row>
	</resultSet>
	<resultSet id="DeltaMergeAndIndexUpdate">
		<row>
			<field name="ID">100</field>
			<field name="VOL">1000</field>
			<field name="SEC_ID">nid999</field>
			<field name="CUST_ID">cust100</field>
		</row>
	</resultSet>
	<!--
		Result expected from EMP.PARTITIONTESTTABLE or EMP.REPLICATEDTESTTABLE
		with FOURTH as 4.
	-->
	<resultSet id="testtable_four">
		<row>
			<field name="ID">1</field>
			<field name="SECONDID">2</field>
			<field name="THIRD">3</field>
			<field name="FOURTH">4</field>
			<field name="FIFTH">10</field>
		</row>
		<row>
			<field name="ID">4</field>
			<field name="SECONDID">5</field>
			<field name="THIRD">6</field>
			<field name="FOURTH">4</field>
			<field name="FIFTH">11</field>
		</row>
		<row>
			<field name="ID">7</field>
			<field name="SECONDID">8</field>
			<field name="THIRD">9</field>
			<field name="FOURTH">4</field>
			<field name="FIFTH">12</field>
		</row>
  </resultSet>
	<!--
		Result expected from TRADE.PORTFOLIO when persistence is enabled
		and index is recovered due to a VM restart 
	-->
	<resultSet id="testBug47945">
		<row>
			<field name="CID">12</field>
			<field name="SID">12</field>
			<field name="SUBTOTAL">12001</field>
    </row>
	</resultSet>
</sqlResults>

=== SnappyDataInc/snappy-store/gemfirexd/tools/src/test/resources/lib/checkHDFSStore.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlResults PUBLIC "-//GemStone Systems, Inc.//GemFireXD Test Results 1.0//EN"
          "sqlResults1_0.dtd">
<sqlResults>
	<resultSet id="empty"/>

	<resultSet id="ddl-dist1">
		<row>
			<field name="NAME">TEST</field>
		</row>
	</resultSet>
        <resultSet id="ddl-altered">
                <row>
                        <field name="NAME">TEST</field>
                        <field name="MAXWRITEONLYFILESIZE">47</field>
                        <field name="WRITEONLYFILEROLLOVERINTERVALSECS">20820</field>
                        <field name="MAXINPUTFILECOUNT">98</field>
                        <field name="MAXINPUTFILESIZE">38</field>
                        <field name="MININPUTFILECOUNT">24</field>
                        <field name="MINORCOMPACT">false</field>
                        <field name="MAJORCOMPACTIONINTERVALMINS">372</field>
                        <field name="MAJORCOMPACT">false</field>
                        <field name="PURGEINTERVALMINS">2392</field>
                        <field name="BATCHSIZE">23</field>
                        <field name="BATCHTIMEINTERVALMILLIS">2000</field>
                        <field name="MINORCOMPACTIONTHREADS">35</field>
                        <field name="MAJORCOMPACTIONTHREADS">29</field>
                        
                </row>
        </resultSet>
        <resultSet id="ddl-original">
                <row>
                        <field name="NAME">TEST</field>
                        <field name="MAXWRITEONLYFILESIZE">256</field>
                        <field name="WRITEONLYFILEROLLOVERINTERVALSECS">3600</field>
                        <field name="MAXINPUTFILECOUNT">10</field>
                        <field name="MAXINPUTFILESIZE">512</field>
                        <field name="MININPUTFILECOUNT">4</field>
                        <field name="MINORCOMPACT">true</field>
                        <field name="MAJORCOMPACTIONINTERVALMINS">720</field>
                        <field name="MAJORCOMPACT">true</field>
                        <field name="PURGEINTERVALMINS">30</field>
                        <field name="BATCHSIZE">32</field>
                        <field name="BATCHTIMEINTERVALMILLIS">60000</field>
                        <field name="MINORCOMPACTIONTHREADS">10</field>
                        <field name="MAJORCOMPACTIONTHREADS">2</field>
                        
                </row>
        </resultSet>
</sqlResults>

=== SnappyDataInc/snappy-store/gemfirexd/tools/src/test/resources/lib/checkStatementQueryDUnit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlResults PUBLIC "-//GemStone Systems, Inc.//GemFireXD Test Results 1.0//EN"
          "sqlResults1_0.dtd">
<sqlResults>
	<!-- The empty result set -->
	<resultSet id="empty" />

	<!--
		Result set expected for first query.
	-->
	<resultSet id="testLikePredicateQuery_1">
		<row>
			<field name="ID">1</field>
		</row>
		<row>
			<field name="ID">2</field>
		</row>
		<row>
			<field name="ID">3</field>
		</row>
		<row>
			<field name="ID">4</field>
		</row>
		<row>
			<field name="ID">5</field>
		</row>
		<row>
			<field name="ID">6</field>
		</row>
		<row>
			<field name="ID">7</field>
		</row>
		<row>
			<field name="ID">8</field>
		</row>
	</resultSet>
	<resultSet id="testLikePredicateQuery_2">
		<row>
			<field name="ID2">1</field>
		</row>
		<row>
			<field name="ID2">2</field>
		</row>
		<row>
			<field name="ID2">3</field>
		</row>
		<row>
			<field name="ID2">4</field>
		</row>
		<row>
			<field name="ID2">5</field>
		</row>
		<row>
			<field name="ID2">6</field>
		</row>
		<row>
			<field name="ID2">7</field>
		</row>
		<row>
			<field name="ID2">8</field>
		</row>
	</resultSet>
	<resultSet id="testBug40626">
	</resultSet>
</sqlResults>

=== SnappyDataInc/snappy-store/gemfirexd/tools/src/test/resources/lib/checkSubquery.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlResults PUBLIC "-//GemStone Systems, Inc.//GemFireXD Test Results 1.0//EN"
          "sqlResults1_0.dtd">
<sqlResults>
	<!-- The empty result set -->
	<resultSet id="empty" />

	
	<resultSet id="subquery_1">
		<row>
			<field name="CID">2</field>
			<field name="TID">2</field>
		</row>
		<row>
			<field name="CID">3</field>
			<field name="TID">3</field>
		</row>
		<row>
			<field name="CID">7</field>
			<field name="TID">7</field>
		</row>
		<row>
			<field name="CID">8</field>
			<field name="TID">8</field>
		</row>
		<row>
			<field name="CID">12</field>
			<field name="TID">12</field>
		</row>
		<row>
			<field name="CID">13</field>
			<field name="TID">13</field>
		</row>
		
	</resultSet>
	
</sqlResults>
