=== SnappyDataInc/snappy-store/gemfirexd/tools/src/test/resources/lib/sqlResults1_0.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
This is the XML DTD for checking the output ResultSet of an SQL query.

All XMLs must include a DOCTYPE of the following form:

  <!DOCTYPE sqlResults PUBLIC
    "-//GemStone Systems, Inc.//GemFireXD Test Results 1.0//EN"
    "sqlResults1_0.dtd">

-->

<!--

The following conventions apply to all file elements unless indicated otherwise.

- In elements that contain PCDATA, leading and trailing whitespace in
  the data may be ignored.

- In elements whose value is an "enumerated type", the value is case
  sensitive.

-->

<!--
The "sqlResults" element is the root element of all the specified ResultSets.
It contains one or more "resultSet" elements each specifying a JDBC
ResultSet object.
-->
<!ELEMENT sqlResults (resultSet+)>

<!--
The "resultSet" element is the root element of the obtained ResultSet.
It must specify an ID attribute to identify a ResultSet. This is so that
a single XML file can specify multiple resultSet elements for different
test results. The optional "ordered" attribute specifies whether the result
is expected to be in exactly the order given in the XML or not.
-->

<!ELEMENT resultSet (row*)>
<!ATTLIST resultSet
  id ID #REQUIRED
  ordered (false | true) #IMPLIED>

<!--
The "row" element contains a single row of the ResultSet.
It contains one or more "field" elements.
-->

<!ELEMENT row (field+)>

<!--
The "field" element is contained within a "row" element and contains
the name and value. It can optionally also specify the type of the
expected object. Normally the value is a simple toString() on the
underlying java object though it can be any string representation
of the object in principle.
-->

<!ELEMENT field (#PCDATA)>
<!ATTLIST field
  name CDATA #REQUIRED
  type CDATA #IMPLIED>

=== SnappyDataInc/snappy-store/gemfirexd/tools/src/test/resources/lib/checkSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlResults PUBLIC "-//GemStone Systems, Inc.//GemFireXD Test Results 1.0//EN"
          "sqlResults1_0.dtd">
<sqlResults>
	<!-- The empty result set -->
	<resultSet id="empty" />
	<!--
		Result set expected when no server group has been given in CREATE
		SCHEMA EMP.
	-->
	<resultSet id="emp_nosg">
		<row>
			<field name="SCHEMANAME">EMP</field>
			<field name="DEFAULTSERVERGROUPS"></field>
			<field name="AUTHORIZATIONID">APP</field>
		</row>
	</resultSet>
	<!--
		Result set expected when server group has been given in CREATE SCHEMA
		EMP. Deliberately changed the order of fields to check that the
		code for unordered checking in XML comparison works correctly.
	-->
	<resultSet id="emp_sg">
		<row>
			<field name="DEFAULTSERVERGROUPS">SG1</field>
			<field name="SCHEMANAME">EMP</field>
		</row>
	</resultSet>
	<!--
		Result set expected when selecting a single test row from a table in
		the EMP schema.
	-->
	<resultSet id="emp_tab_sel">
		<row>
			<field name="ID">1</field>
			<field name="DESCRIPTION">First</field>
		</row>
	</resultSet>
</sqlResults>

=== SnappyDataInc/snappy-store/gemfirexd/tools/src/test/resources/lib/checkTableIndicesConsistency.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sqlResults PUBLIC "-//GemStone Systems, Inc.//GemFireXD Test Results 1.0//EN"
          "sqlResults1_0.dtd">
<sqlResults>
	<resultSet id="rs1">
	 <row>
         <field name="ID">1</field>
         <field name="SECONDID">2</field>
         <field name="THIRD">3</field>
         <field name="FOURTH">4</field>
         <field name="FIFTH">10</field>
   </row>
	<row>
		 <field name="ID">4</field>
         <field name="SECONDID">5</field>
         <field name="THIRD">6</field>
         <field name="FOURTH">4</field>
         <field name="FIFTH">11</field>
   </row>
  
   <row>
         <field name="ID">7</field>
         <field name="SECONDID">8</field>
         <field name="THIRD">9</field>
         <field name="FOURTH">4</field>
         <field name="FIFTH">12</field>
						
	</row>		
	</resultSet>
</sqlResults>
